### ISSUE TITLE
[🐛 BUG] Status of scenario viewer not updated

### ISSUE THREAD

**Issue by FlorianJacta** [Avaiga/taipy#1669]
### What went wrong? 🤔

I receive that the predictions is ready but the scenario viewer tells me that the scenario is still running.

### Expected Behavior

The status should be completed.

### Steps to Reproduce Issue

This issue is hard to reproduce. I tried creating some code but failed to reproduce the error. You should be able to reproduce it with this demo https://github.com/Avaiga/demo-covid-dashboard

Run the code, create a scenario, submit it, and observe its status. If the issue is not found, submit it again.

I have tried with 4.0.0.dev0. It may have been fixed in the latest develop version but I cannot install it.

### Version of Taipy

4.0.0.dev0

### Acceptance Criteria

- [ ] Ensure new code is unit tested, and check code coverage is at least 90%.
- [ ] Create related issue in taipy-doc for documentation and Release Notes.

### Code of Conduct

- [X] I have checked the [existing issues](https://github.com/Avaiga/taipy/issues?q=is%3Aissue+).
- [ ] I am willing to work on this issue (optional)

**Comment by FlorianJacta** [comment]
This code replicates the issue on my side. This is the develop version of Taipy (8/23/24).

```python
from taipy import Config

import taipy as tp
import pandas as pd


def identity(input):
    print("     Identity")
    return input


Config.configure_job_executions(mode="standalone", max_nb_of_workers=2)

## Input Data Nodes
input_cfg = Config.configure_data_node(id="input_dn", default_data=2)

## Remaining Data Node
output_cfg = Config.configure_data_node(id="output_dn")

# Task config objects
identity_task_cfg = Config.configure_task(
    id="identity", function=identity, input=input_cfg, output=output_cfg, skippable=True
)


# Configure our scenario config.
scenario_cfg = Config.configure_scenario(
    id="my_scenario", task_configs=[identity_task_cfg]
)

scenario = None

page = """
<|{scenario}|scenario_selector|>
<|{scenario}|scenario|>

<|job_selector|>
"""

pages = {"/": "<|navbar|> <|toggle|theme|> <br/>", "Data-Node": page}


if __name__ == "__main__":
    tp.Orchestrator().run()

    tp.Gui(pages=pages).run()
```

**Comment by jrobinAV** [comment]
It should be tested again since some related code has been changed.

**Comment by FlorianJacta** [comment]
Same issue in Taipy 4.0.0.dev2:

![image](https://github.com/user-attachments/assets/e8a44f8c-48c9-4942-a1cd-8eb2cf0602dd)
