### ISSUE TITLE
[🐛 BUG] De-synchronized front-ends and  back-end  

### ISSUE THREAD

**Issue by jrobinAV** [Avaiga/taipy#2344]
### What went wrong? 🤔
Front-ends get de-synchronized when re-running an application.

This is more important than it looks like, as it happens frequently and gives users the wrong impression that their application has a bug. 

For example, it happens frequently during an application's development phase, especially with the default behavior of Gui().run(), which opens a new tab without closing the previous tabs.

It also happens when re-deploying a live application, causing the wrong error messages at a very bad time.

### Reproduce the situation

The problem arises when:

- We run an application.
- We access the application on a browser tab.
- We shut down the application without closing the tab.
- We re-run the application (or another application on the same port).
- We use the same old tab that does not correspond to the new back-end application. This may create errors, warnings, or inconsistencies.

### Expected Behavior

De-synchronized front-ends should be aware that the back-end version they are connected to is incorrect. The front-end application should automatically display a message to let the user know he/she should refresh the browser.

### Solution Proposed

What about generating a unique identifier each time we run the server? It could represent a `run_identifier`. Each of the clients (the tabs) could know this unique `run_identifier`. 
The clients could pass the `run_identifier` to the back end every time it communicates with it. On the server side, the client request is properly rejected if the `run_identifier` received from the client does not match its own internal `run_identifier`. The front end should be able to display a message asking the user to refresh the tab.

### Version of Taipy

- 3.X,
- 4.Y,
- develop

### Linked issues
- https://github.com/Avaiga/taipy-enterprise/issues/574

### Acceptance Criteria

- [ ] A unit test reproducing the bug is added.
- [ ] Any new code is covered by a unit tested.
- [ ] Check code coverage is at least 90%.
- [ ] The bug reporter validated the fix.
- [ ] Related issue(s) in taipy-doc are created for documentation and Release Notes are updated.

### Code of Conduct

- [x] I have checked the [existing issues](https://github.com/Avaiga/taipy/issues?q=is%3Aissue+).
- [ ] I am willing to work on this issue (optional)

**Comment by dinhlongviolin1** [comment]
@FredLL-Avaiga Here is the previous implementation of App Id
WS Type declaration https://github.com/Avaiga/taipy/blob/develop/taipy/gui/types.py#L46
WS Handler 
- https://github.com/Avaiga/taipy/blob/develop/taipy/gui/gui.py#L729-L730
- https://github.com/Avaiga/taipy/blob/develop/taipy/gui/gui.py#L1338-L1352

**Comment by FredLL-Avaiga** [comment]
@jrobinAV you can specify `app_id=True` in `Gui.run()`

**Comment by jrobinAV** [comment]
> [@jrobinAV](https://github.com/jrobinAV) you can specify `app_id=True` in `Gui.run()`

ok, thanks @FredLL-Avaiga . I am going to test it with @FlorianJacta.
 
Is there any reason why we want to set it to False?
If yes, is it on purpose not to make it the default behavior?

**Comment by FredLL-Avaiga** [comment]
I knew you would say this 😜

**Comment by FredLL-Avaiga** [comment]
Default behavior is unchanged
After 10B tests we might change it

**Comment by jrobinAV** [comment]
@FabienLelaquais what do you think?

**Comment by FredLL-Avaiga** [comment]
let's discuss
- default app_id value to True (change app_id name ?)
- adding frontend console message
@FabienLelaquais

**Comment by FabienLelaquais** [comment]
> let's discuss
> 
> * default app_id value to True (change app_id name ?)
> * adding frontend console message
>   [@FabienLelaquais](https://github.com/FabienLelaquais)

- app_id -> gui_addr
- 'adding frontend console message' oh yes oh yes
