### ISSUE TITLE
Add new visual elements

### ISSUE THREAD

**Issue by FlorianJacta** [Avaiga/taipy#436]
**What would that feature address**
The possibility to use more visual elements in Taipy.

***Description of the ideal solution***
Integrate as visual elements (they are sorted by importance):

- [x] Stat/Metric: [maybe this](https://mui.com/toolpad/reference/components/metric/) | Issue: #551

![image](https://github.com/Avaiga/taipy-gui/assets/98709993/7e4466e2-f085-4f00-8753-7f8e280b2d17)

- [x]  Progress bar/circle: [example](https://mui.com/material-ui/react-progress/)  | Issue: #692

![image](https://github.com/Avaiga/taipy-gui/assets/98709993/ad829356-ea17-48cc-9133-8ad1fdcbc001)

- [ ]  Alert: not a notification. A visual element in the application that doesn't go away. [example](https://mui.com/material-ui/react-alert/) | Issue: #693 

![image](https://github.com/Avaiga/taipy-gui/assets/98709993/ef9b883a-8189-427c-8739-160b04d18c20)

- [x]  Switch: [example](https://mui.com/material-ui/react-switch/) | Issue: #691

![image](https://github.com/Avaiga/taipy-gui/assets/98709993/1c6d4875-04c7-4208-afba-934fe45b562b)

- [x]  Radio: [radio](https://mui.com/material-ui/react-radio-button/#radio-group) | Issue: #689

![image](https://github.com/Avaiga/taipy-gui/assets/98709993/98c1ebfc-ee92-4368-9aae-fbea718b6a16)

- [x]  Checkbox: [checkbox](https://mui.com/material-ui/react-checkbox/#basic-checkboxes) | Issue: #690

![image](https://github.com/Avaiga/taipy-gui/assets/98709993/0d11b9b1-6a9e-4f7d-ba12-962e743b0e25)

**Acceptance Criteria**
- [ ] Ensure new code is unit tested, and check code coverage is at least 90%
- [ ] Propagate any change on the demos and run all of them to ensure there is no breaking change
- [ ] Ensure any change is well documented

**Comment by FlorianJacta** [comment]
Some people asked about the checkbox and said it was missing.

**Comment by FlorianJacta** [comment]
A user asked about radio buttons. We should really look into these new visual elements as people are asking them. @FredLL-Avaiga We can decompose this issue if you'd like

**Comment by FredLL-Avaiga** [comment]
good idea, Create one for radio (it would likely be a selector with a new way of rendering)
What do you think @FabienLelaquais ?

**Comment by FabienLelaquais** [comment]
Agreed.
Radio = selector. Can this be achieved with CSS only? (🤞)

And sure, one issue per new element type or predefined style for an existing element would make things far easier to track.

**Comment by FlorianJacta** [comment]
Can we make an issue covering multiple issues?  I like this one to keep track of the new visual elements. I can add other issues into the description of this one or is it bad practice?

**Comment by FredLL-Avaiga** [comment]
CSS don't think so
but I might add some classes to display radio in line or column

**Comment by jrobinAV** [comment]
It has been split into multiple issues.
